# Generated by Django 3.2.4 on 2021-07-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_publicacion',
        ),
    ]
