# Generated by Django 3.2.4 on 2021-07-07 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_remove_producto_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 21, 25, 1, 992538, tzinfo=utc)),
        ),
    ]
