# Generated by Django 3.2.4 on 2021-07-07 22:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_alter_producto_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 22, 59, 29, 348964, tzinfo=utc)),
        ),
    ]
